'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const { JSDOM } = require('jsdom');
const root = path.resolve(__dirname, '..');
const dom = new JSDOM('<canvas id="particle-network" aria-hidden="true"></canvas><form id="profile-form"><input type="email" name="email" required></form>', { url: 'http://localhost/escola/', runScripts: 'outside-only', pretendToBeVisual: true });
const w = dom.window;
const run = code => vm.runInContext(code, dom.getInternalVMContext());
run(fs.readFileSync(path.join(root, 'assets/js/email-validation.js'), 'utf8'));
for (const value of ['usuario@gmail.com', 'nome.sobrenome@outlook.com', 'aluno@colegio.com.br', 'nome+turma@gmail.com']) assert.equal(run(`EmailValidation.valid(${JSON.stringify(value)})`), true);
for (const value of ['usuario@','usuario','@gmail.com','usuario@gmail','usuario gmail.com','a..b@gmail.com','.nome@gmail.com','nome.@gmail.com','a@-gmail.com','a@gmail..com','a'.repeat(65)+'@gmail.com']) assert.equal(run(`EmailValidation.valid(${JSON.stringify(value)})`), false);
const input = w.document.querySelector('input'); input.value='usuario@gmail';
const event = new w.Event('submit', { bubbles: true, cancelable: true });
w.document.querySelector('form').dispatchEvent(event); assert.ok(event.defaultPrevented);
input.value='usuario@gmail.com';input.dispatchEvent(new w.Event('input', { bubbles: true })); assert.ok(input.checkValidity());
let arcs=0, lastRatio=0, fill='', next=0, callbacks=new Map(), reducedListener;
const context={ clearRect(){arcs=0;}, setTransform(ratio){lastRatio=ratio;}, beginPath(){}, moveTo(){}, lineTo(){}, stroke(){}, arc(){arcs++;}, fill(){}, set fillStyle(value){fill=value;} };
w.HTMLCanvasElement.prototype.getContext=()=>context;
const reduced={ matches:false, addEventListener(name,callback){reducedListener=callback;} };
w.matchMedia=()=>reduced;
w.requestAnimationFrame=callback=>{callbacks.set(++next,callback);return next;};
w.cancelAnimationFrame=id=>callbacks.delete(id);
Object.defineProperty(w,'devicePixelRatio',{value:3,configurable:true});
run(fs.readFileSync(path.join(root, 'assets/js/particles.js'), 'utf8'));
assert.ok(arcs>=16 && arcs<=80);assert.ok(lastRatio<=2);assert.equal(callbacks.size,1);
const desktop=arcs;w.innerWidth=375;w.innerHeight=667;w.dispatchEvent(new w.Event('resize'));assert.ok(arcs<=28 && arcs<desktop);
reduced.matches=true;reducedListener();assert.equal(callbacks.size,0);assert.ok(arcs>0);
Object.defineProperty(w.document,'hidden',{value:true,configurable:true});reduced.matches=false;reducedListener();assert.equal(callbacks.size,0);
Object.defineProperty(w.document,'hidden',{value:false,configurable:true});w.document.dispatchEvent(new w.Event('visibilitychange'));assert.equal(callbacks.size,1);
(async()=>{w.document.documentElement.dataset.theme='dark';await Promise.resolve();assert.match(fill,/204,222,239/);w.document.documentElement.dataset.theme='light';await Promise.resolve();assert.match(fill,/87,127,160/);dom.window.close();console.log('OK: email format, submit prevention, canvas density, DPI, theme, reduced motion and tab visibility.');})();
