<?php
declare(strict_types=1);
function userView(array $u,?array $links=null): array {
    $teacher=$links!==null?$links['teacherId']:teacherId($u);
    $students=$links!==null?$links['studentIds']:(in_array($u['cargo'],['aluno','responsavel'])?permittedStudents($u):[]);
    return ['id'=>(string)$u['id'],'name'=>$u['nome'],'email'=>$u['email'],'emailVerified'=>(bool)($u['email_verificado']??false),'emailVerificationRequired'=>!emailAccessAllowed($u),'pendingEmail'=>$u['email_pendente']??'','verificationSent'=>!empty($u['verificacao_enviada_em']),'role'=>$u['cargo'],'status'=>ucfirst($u['status']),'mustChangePassword'=>(bool)$u['primeiro_acesso'],'lastAccess'=>iso($u['ultimo_acesso']),'teacherId'=>$teacher,'studentIds'=>array_map('strval',$students),'phone'=>$u['telefone'],'photo'=>$u['foto']??'','notifications'=>(bool)$u['notificacoes']];
}
function enrollmentView(array $r): array {
    $map=['name'=>'nome_aluno','birth'=>'data_nascimento','cpf'=>'cpf_aluno','rg'=>'rg_aluno','phone'=>'telefone_aluno','email'=>'email_aluno','cep'=>'cep','street'=>'logradouro','number'=>'numero','complement'=>'complemento','district'=>'bairro','city'=>'cidade','state'=>'estado','guardianName'=>'nome_responsavel','guardianCpf'=>'cpf_responsavel','kinship'=>'parentesco','guardianPhone'=>'telefone_responsavel','guardianEmail'=>'email_responsavel','requestedGrade'=>'serie_pretendida','requestedPeriod'=>'periodo','year'=>'ano_letivo','previousSchool'=>'escola_anterior','note'=>'observacoes','loginEmail'=>'email_acesso','rejectionReason'=>'motivo_reprovacao'];
    $v=['id'=>(string)$r['id'],'status'=>['email_nao_verificado'=>'Pendente','pendente'=>'Pendente','em_analise'=>'Em análise','aprovada'=>'Aprovada','reprovada'=>'Reprovada','cancelada'=>'Cancelada'][$r['status']],'createdAt'=>iso($r['criado_em']),'reviewedAt'=>iso($r['analisado_em']),'reviewedBy'=>(string)($r['analisado_por']??''),'studentId'=>(string)($r['aluno_id']??'')];foreach($map as $k=>$col)$v[$k]=$r[$col]??'';return $v;
}
function snapshot(array $u): array {
    $out=['user'=>userView($u),'settings'=>settings(),'csrf'=>csrfToken(),'serverTime'=>date(DATE_ATOM),'read'=>new stdClass()];
    foreach(['users','students','teachers','classes','subjects','grades','attendance','activities','contents','occurrences','announcements','enrollments','timeRecords','adjustments','schedules','notifications','logs','years','terms','evaluations','links','gradeEntries','frequencies'] as $key)$out[$key]=[];
    if(!emailAccessAllowed($u))return $out;
    if($u['cargo']==='diretor'||$u['status']==='pendente')$out['enrollments']=array_map('enrollmentView',rows('SELECT * FROM solicitacoes_matricula'.($u['cargo']==='diretor'?'':' WHERE usuario_id=?').' ORDER BY id DESC',$u['cargo']==='diretor'?[]:[$u['id']]));
    if($u['status']!=='ativo'||$u['primeiro_acesso'])return $out;
    if(isManager($u)){
        $counts=one("SELECT (SELECT COUNT(*) FROM alunos WHERE status='ativo') students, (SELECT COUNT(*) FROM professores WHERE status='ativo') teachers, (SELECT COUNT(*) FROM turmas WHERE status='ativo') classes, (SELECT COUNT(*) FROM solicitacoes_matricula WHERE status='pendente') pending, (SELECT COUNT(*) FROM ocorrencias WHERE status<>'inativo' AND data_ocorrencia>=DATE_FORMAT(CURRENT_DATE,'%Y-%m-01')) occurrences, (SELECT COUNT(*) FROM pontos_professores WHERE data=CURRENT_DATE) present, (SELECT COUNT(*) FROM atividades WHERE status NOT IN ('Encerrada','inativo')) activities");
        $out['metrics']=array_map('intval',$counts);
    }
    $manager=isManager($u);$tid=teacherId($u);$studentIds=array_map('strval',permittedStudents($u));$classIds=array_map('strval',permittedClasses($u));
    $hasClass=fn($id)=>in_array((string)$id,$classIds,true);$hasStudent=fn($id)=>in_array((string)$id,$studentIds,true);
    $allLinks=rows('SELECT * FROM professor_turma');$classSubjects=rows('SELECT * FROM turma_disciplina');
    $ownLink=fn($c,$s)=>$u['cargo']!=='professor'||count(array_filter($allLinks,fn($l)=>(string)$l['professor_id']===$tid&&(string)$l['turma_id']===(string)$c&&(string)$l['disciplina_id']===(string)$s))>0;
    foreach(rows('SELECT * FROM turmas') as $c){if(!$hasClass($c['id']))continue;$subjects=array_values(array_unique(array_map(fn($l)=>(string)$l['disciplina_id'],array_filter($classSubjects,fn($l)=>(string)$l['turma_id']===(string)$c['id']&&$ownLink($c['id'],$l['disciplina_id'])))));$out['classes'][]=['id'=>(string)$c['id'],'name'=>$c['nome'],'course'=>$c['curso'],'series'=>$c['serie'],'period'=>$c['periodo'],'year'=>(int)$c['ano_letivo'],'room'=>$c['sala'],'capacity'=>(int)$c['capacidade'],'teacherId'=>(string)($c['professor_responsavel_id']??''),'subjectIds'=>$subjects,'status'=>$c['status']==='ativo'?'Ativa':'Inativa'];}
    $visibleSubjects=array_unique(array_merge([], ...array_column($out['classes'],'subjectIds')));
    foreach(rows('SELECT * FROM disciplinas') as $s)if($manager||in_array((string)$s['id'],$visibleSubjects,true))$out['subjects'][]=['id'=>(string)$s['id'],'name'=>$s['nome'],'code'=>$s['codigo']??'','workload'=>(float)$s['carga_horaria'],'status'=>ucfirst($s['status'])];
    $teacherSubjects=rows('SELECT * FROM professor_disciplina');
    foreach(rows('SELECT p.*,u.nome,u.email FROM professores p JOIN usuarios u ON u.id=p.usuario_id') as $t){$links=array_filter($allLinks,fn($l)=>(string)$l['professor_id']===(string)$t['id']);$cls=array_values(array_unique(array_map(fn($l)=>(string)$l['turma_id'],$links)));if(!$manager&&($u['cargo']==='professor'?(string)$t['id']!==$tid:!array_intersect($cls,$classIds)))continue;$out['teachers'][]=['id'=>(string)$t['id'],'name'=>$t['nome'],'email'=>$manager||$u['cargo']==='professor'?$t['email']:'','registration'=>$t['matricula']??'','phone'=>$manager?$t['telefone']:'','cpf'=>$manager?($t['cpf']??''):'','birth'=>$manager?($t['data_nascimento']??''):'','workload'=>(float)$t['carga_horaria'],'startTime'=>substr($t['horario_previsto']??'',0,5),'classIds'=>$manager?$cls:array_values(array_intersect($cls,$classIds)),'subjectIds'=>array_values(array_unique(array_map(fn($l)=>(string)$l['disciplina_id'],array_filter($teacherSubjects,fn($l)=>(string)$l['professor_id']===(string)$t['id'])))),'status'=>ucfirst($t['status'])];}
    $sql="SELECT a.*,at.turma_id,r.nome guardian_name,r.email guardian_email,r.telefone guardian_phone,ra.parentesco FROM alunos a LEFT JOIN aluno_turma at ON at.aluno_id=a.id AND at.status='ativo' LEFT JOIN responsavel_aluno ra ON ra.aluno_id=a.id AND ra.responsavel_principal=1 LEFT JOIN responsaveis r ON r.id=ra.responsavel_id";
    foreach(rows($sql) as $s){if(!$hasStudent($s['id']))continue;$out['students'][]=['id'=>(string)$s['id'],'name'=>$s['nome'],'registration'=>$s['matricula'],'classId'=>(string)($s['turma_id']??''),'birth'=>$u['cargo']==='professor'?'':$s['data_nascimento'],'cpf'=>$u['cargo']==='professor'?'':$s['cpf'],'email'=>$u['cargo']==='professor'?'':$s['email'],'phone'=>$u['cargo']==='professor'?'':$s['telefone'],'address'=>$u['cargo']==='professor'?'':($s['endereco_formatado']?:$s['logradouro'].', '.$s['numero'].' — '.$s['cidade'].'/'.$s['estado']),'guardianName'=>$s['guardian_name']??'','guardianEmail'=>$u['cargo']==='professor'?'':($s['guardian_email']??''),'guardianPhone'=>$u['cargo']==='professor'?'':($s['guardian_phone']??''),'kinship'=>$s['parentesco']??'','entry'=>$s['data_ingresso'],'photo'=>$s['foto']??'','status'=>ucfirst($s['status'])];}
    foreach(rows('SELECT av.*,b.numero,b.ano_letivo_id FROM avaliacoes av JOIN bimestres b ON b.id=av.bimestre_id') as $a){if(!$hasClass($a['turma_id'])||!$ownLink($a['turma_id'],$a['disciplina_id'])||$u['cargo']==='professor'&&(string)$a['professor_id']!==$tid)continue;$out['evaluations'][]=['id'=>(string)$a['id'],'name'=>$a['titulo'],'title'=>$a['titulo'],'classId'=>(string)$a['turma_id'],'subjectId'=>(string)$a['disciplina_id'],'teacherId'=>(string)$a['professor_id'],'termId'=>(string)$a['bimestre_id'],'term'=>(int)$a['numero'],'type'=>$a['tipo'],'maximum'=>(float)$a['valor_maximo'],'date'=>$a['data_avaliacao']];}
    $evalById=array_column($out['evaluations'],null,'id');$group=[];
    foreach(rows('SELECT * FROM notas') as $n){$a=$evalById[$n['avaliacao_id']]??null;if(!$a||!$hasStudent($n['aluno_id']))continue;$out['gradeEntries'][]=['id'=>(string)$n['id'],'evaluationId'=>(string)$n['avaliacao_id'],'studentId'=>(string)$n['aluno_id'],'value'=>(float)$n['nota'],'note'=>$n['observacao']??''];$key=$n['aluno_id'].'-'.$a['classId'].'-'.$a['subjectId'].'-'.$a['term'];$group[$key]??=['id'=>$key,'studentId'=>(string)$n['aluno_id'],'classId'=>$a['classId'],'subjectId'=>$a['subjectId'],'term'=>$a['term'],'values'=>[],'recovery'=>null];$value=(float)$n['nota']/$a['maximum']*10;if($a['type']==='recuperacao')$group[$key]['recovery']=max($group[$key]['recovery']??0,$value);else $group[$key]['values'][]=$value;}
    $out['grades']=array_values($group);
    foreach(rows('SELECT pr.*,c.turma_id,c.disciplina_id,c.professor_id,c.data_aula,c.numero_aula FROM presencas pr JOIN chamadas c ON c.id=pr.chamada_id') as $p)if($hasStudent($p['aluno_id'])&&$ownLink($p['turma_id'],$p['disciplina_id']))$out['attendance'][]=['id'=>(string)$p['id'],'studentId'=>(string)$p['aluno_id'],'classId'=>(string)$p['turma_id'],'subjectId'=>(string)$p['disciplina_id'],'teacherId'=>(string)$p['professor_id'],'date'=>$p['data_aula'],'lesson'=>(string)$p['numero_aula'],'status'=>['presente'=>'P','falta'=>'F','justificada'=>'J'][$p['status']],'note'=>$p['observacao']];
    // A frequência é agregada no MySQL; não é gravada como porcentagem.
    foreach(rows("SELECT pr.aluno_id, c.disciplina_id, c.turma_id, COUNT(*) total, SUM(pr.status='presente') present, SUM(pr.status='falta') absent, SUM(pr.status='justificada') justified FROM presencas pr JOIN chamadas c ON c.id=pr.chamada_id GROUP BY pr.aluno_id,c.disciplina_id,c.turma_id") as $f)if($hasStudent($f['aluno_id'])&&$ownLink($f['turma_id'],$f['disciplina_id']))$out['frequencies'][]=['studentId'=>(string)$f['aluno_id'],'subjectId'=>(string)$f['disciplina_id'],'total'=>(int)$f['total'],'present'=>(int)$f['present'],'absent'=>(int)$f['absent'],'justified'=>(int)$f['justified']];
    foreach(['activities'=>'atividades','contents'=>'conteudos_aulas'] as $key=>$table)foreach(rows("SELECT * FROM $table WHERE status<>'inativo'") as $r){if(!$hasClass($r['turma_id'])||!$ownLink($r['turma_id'],$r['disciplina_id'])||$u['cargo']==='professor'&&(string)$r['professor_id']!==$tid)continue;$v=['id'=>(string)$r['id'],'title'=>$r['titulo'],'classId'=>(string)$r['turma_id'],'subjectId'=>(string)$r['disciplina_id'],'teacherId'=>(string)$r['professor_id'],'description'=>$r['descricao'],'status'=>$r['status'],'material'=>$r['material']];if($key==='activities')$v+=['created'=>$r['data_publicacao'],'due'=>$r['data_entrega'],'value'=>(float)$r['valor'],'type'=>$r['tipo'],'attachment'=>$r['material']];else $v+=['date'=>$r['data_aula'],'lesson'=>(string)$r['numero_aula'],'objective'=>$r['objetivo'],'methodology'=>$r['metodologia'],'note'=>$r['observacao']??''];$out[$key][]=$v;}
    foreach(rows("SELECT * FROM ocorrencias WHERE status<>'inativo'") as $r)if($hasStudent($r['aluno_id'])&&($u['cargo']!=='professor'||(string)$r['registrado_por']===(string)$u['id']))$out['occurrences'][]=['id'=>(string)$r['id'],'studentId'=>(string)$r['aluno_id'],'classId'=>(string)$r['turma_id'],'teacherId'=>(string)($r['professor_id']??''),'category'=>$r['categoria'],'description'=>$r['descricao'],'note'=>$r['observacao']??'','date'=>$r['data_ocorrencia'],'status'=>$r['status']];
    $audiences=['todos'=>'Todos','professores'=>'Professores','alunos'=>'Alunos','responsaveis'=>'Responsáveis','turma'=>'Turma específica','diretores'=>'Diretores','coordenadores'=>'Coordenadores'];$public=['diretor'=>'diretores','coordenador'=>'coordenadores','professor'=>'professores','aluno'=>'alunos','responsavel'=>'responsaveis'][$u['cargo']];
    foreach(rows("SELECT c.*,u.nome autor FROM comunicados c JOIN usuarios u ON u.id=c.autor_id WHERE c.status='ativo' AND c.data_publicacao<=CURRENT_DATE ORDER BY c.data_publicacao DESC") as $r)if($manager||$r['publico']==='todos'||$r['publico']===$public||$r['publico']==='turma'&&$hasClass($r['turma_id']))$out['announcements'][]=['id'=>(string)$r['id'],'title'=>$r['titulo'],'description'=>$r['mensagem'],'audience'=>$audiences[$r['publico']],'classId'=>(string)($r['turma_id']??''),'date'=>$r['data_publicacao'],'author'=>$r['autor'],'pinned'=>(bool)$r['destaque']];
    if(in_array($u['cargo'],['diretor','professor'])){foreach(rows('SELECT * FROM pontos_professores'.($u['cargo']==='professor'?' WHERE professor_id=?':''),$u['cargo']==='professor'?[$tid]:[]) as $r)$out['timeRecords'][]=['id'=>(string)$r['id'],'teacherId'=>(string)$r['professor_id'],'date'=>$r['data'],'entry'=>iso($r['entrada']),'exit'=>iso($r['saida']),'status'=>$r['status']];foreach(rows('SELECT a.*,p.data FROM solicitacoes_ajuste_ponto a JOIN pontos_professores p ON p.id=a.ponto_id'.($u['cargo']==='professor'?' WHERE a.professor_id=?':''),$u['cargo']==='professor'?[$tid]:[]) as $r)$out['adjustments'][]=['id'=>(string)$r['id'],'teacherId'=>(string)$r['professor_id'],'date'=>$r['data'],'entry'=>iso($r['entrada_solicitada']),'exit'=>iso($r['saida_solicitada']),'reason'=>$r['motivo'],'status'=>['pendente'=>'Pendente','aprovado'=>'Aprovada','rejeitado'=>'Reprovada'][$r['status']],'reviewReason'=>$r['parecer']??''];}
    foreach(rows('SELECT * FROM horarios_aulas') as $r)if($hasClass($r['turma_id'])&&($u['cargo']!=='professor'||(string)$r['professor_id']===$tid))$out['schedules'][]=['id'=>(string)$r['id'],'name'=>substr($r['hora_inicio'],0,5),'teacherId'=>(string)$r['professor_id'],'classId'=>(string)$r['turma_id'],'subjectId'=>(string)$r['disciplina_id'],'weekday'=>(int)$r['dia_semana'],'start'=>substr($r['hora_inicio'],0,5),'end'=>substr($r['hora_fim'],0,5),'room'=>$r['sala']];
    foreach(rows('SELECT * FROM notificacoes WHERE usuario_id=? ORDER BY id DESC LIMIT 200',[$u['id']]) as $r)$out['notifications'][]=['id'=>(string)$r['id'],'text'=>$r['titulo'].($r['mensagem']?' — '.$r['mensagem']:''),'route'=>$r['link'],'date'=>iso($r['criado_em']),'read'=>(bool)$r['lida']];
    if($u['cargo']==='diretor'){
        $teacherByUser=array_column(rows('SELECT usuario_id,id FROM professores'),'id','usuario_id');$studentByUser=[];
        foreach(rows('SELECT usuario_id,id aluno_id FROM alunos UNION SELECT r.usuario_id,ra.aluno_id FROM responsaveis r JOIN responsavel_aluno ra ON ra.responsavel_id=r.id') as $link)$studentByUser[$link['usuario_id']][]=(string)$link['aluno_id'];
        foreach(rows('SELECT * FROM usuarios') as $user)$out['users'][]=userView($user,['teacherId'=>(string)($teacherByUser[$user['id']]??''),'studentIds'=>$studentByUser[$user['id']]??[]]);
        foreach(rows('SELECT l.*,u.nome FROM logs_auditoria l LEFT JOIN usuarios u ON u.id=l.usuario_id ORDER BY l.id DESC LIMIT 500') as $r)$out['logs'][]=['id'=>(string)$r['id'],'text'=>($r['nome']??'Sistema').' · '.$r['acao'],'date'=>iso($r['criado_em']),'entity'=>$r['entidade'],'entityId'=>$r['entidade_id'],'details'=>$r['descricao']];
    }
    foreach(rows('SELECT * FROM anos_letivos') as $r)$out['years'][]=['id'=>(string)$r['id'],'name'=>(string)$r['ano'],'year'=>(int)$r['ano'],'start'=>$r['data_inicio'],'end'=>$r['data_fim'],'status'=>$r['status']];
    foreach(rows('SELECT b.*,a.ano FROM bimestres b JOIN anos_letivos a ON a.id=b.ano_letivo_id') as $r)$out['terms'][]=['id'=>(string)$r['id'],'name'=>$r['ano'].' · '.$r['nome'],'yearId'=>(string)$r['ano_letivo_id'],'number'=>(int)$r['numero'],'start'=>$r['data_inicio'],'end'=>$r['data_fim'],'status'=>$r['status']];
    if($manager)foreach($allLinks as $r)$out['links'][]=['id'=>(string)$r['id'],'name'=>'Vínculo '.$r['id'],'teacherId'=>(string)$r['professor_id'],'classId'=>(string)$r['turma_id'],'subjectId'=>(string)$r['disciplina_id']];
    return $out;
}
