-- Colégio Legado: MySQL/MariaDB, sem dados acadêmicos iniciais.
CREATE DATABASE IF NOT EXISTS colegio_legado CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE colegio_legado;
SET NAMES utf8mb4;
CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email_verificado BOOLEAN NOT NULL DEFAULT 0,
  email_verificacao_exigida BOOLEAN NOT NULL DEFAULT 0,
  email_verificado_em DATETIME NULL,
  email_pendente VARCHAR(190) NULL,
  token_verificacao CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  token_expira_em DATETIME NULL,
  verificacao_solicitada_em DATETIME NULL,
  verificacao_enviada_em DATETIME NULL,
  UNIQUE INDEX uq_email_token (token_verificacao),
  UNIQUE INDEX uq_email_pendente (email_pendente),
  nome VARCHAR(200) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, senha_hash VARCHAR(255) NOT NULL, cargo ENUM('diretor','coordenador','professor','aluno','responsavel') NOT NULL, status ENUM('ativo','inativo','bloqueado','pendente') NOT NULL DEFAULT 'ativo', primeiro_acesso BOOLEAN NOT NULL DEFAULT 0, ultimo_acesso DATETIME NULL, telefone VARCHAR(25) NOT NULL DEFAULT '', foto MEDIUMTEXT NULL, notificacoes BOOLEAN NOT NULL DEFAULT 1, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS diretores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, cpf CHAR(11) NULL UNIQUE, telefone VARCHAR(25) NOT NULL DEFAULT '', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS coordenadores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, cpf CHAR(11) NULL UNIQUE, telefone VARCHAR(25) NOT NULL DEFAULT '', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS professores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, matricula VARCHAR(40) NULL UNIQUE, cpf CHAR(11) NULL UNIQUE, telefone VARCHAR(25) NOT NULL DEFAULT '', data_nascimento DATE NULL, data_admissao DATE NULL, carga_horaria DECIMAL(6,2) NOT NULL DEFAULT 0, horario_previsto TIME NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS alunos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, matricula VARCHAR(40) NOT NULL UNIQUE, nome VARCHAR(200) NOT NULL, cpf CHAR(11) NULL UNIQUE, rg VARCHAR(30) NOT NULL DEFAULT '', data_nascimento DATE NOT NULL, telefone VARCHAR(25) NOT NULL, email VARCHAR(190) NOT NULL, cep VARCHAR(9) NOT NULL, logradouro VARCHAR(200) NOT NULL, numero VARCHAR(20) NOT NULL, complemento VARCHAR(150) NOT NULL DEFAULT '', bairro VARCHAR(100) NOT NULL, cidade VARCHAR(100) NOT NULL, estado CHAR(2) NOT NULL, endereco_formatado VARCHAR(500) NULL, foto MEDIUMTEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo', data_ingresso DATE NOT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS responsaveis (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, nome VARCHAR(200) NOT NULL, cpf CHAR(11) NOT NULL UNIQUE, telefone VARCHAR(25) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS responsavel_aluno (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  responsavel_id BIGINT UNSIGNED NOT NULL, aluno_id BIGINT UNSIGNED NOT NULL, parentesco VARCHAR(40) NOT NULL, responsavel_principal BOOLEAN NOT NULL DEFAULT 1,
  UNIQUE (responsavel_id,aluno_id),
  FOREIGN KEY (responsavel_id) REFERENCES responsaveis(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS solicitacoes_matricula (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, aluno_id BIGINT UNSIGNED NULL, nome_aluno VARCHAR(200) NOT NULL, cpf_aluno CHAR(11) NOT NULL, rg_aluno VARCHAR(30) NOT NULL DEFAULT '', data_nascimento DATE NOT NULL, telefone_aluno VARCHAR(25) NOT NULL, email_aluno VARCHAR(190) NOT NULL, cep VARCHAR(9) NOT NULL, logradouro VARCHAR(200) NOT NULL, numero VARCHAR(20) NOT NULL, complemento VARCHAR(150) NOT NULL DEFAULT '', bairro VARCHAR(100) NOT NULL, cidade VARCHAR(100) NOT NULL, estado CHAR(2) NOT NULL, nome_responsavel VARCHAR(200) NOT NULL, cpf_responsavel CHAR(11) NOT NULL, parentesco VARCHAR(40) NOT NULL, telefone_responsavel VARCHAR(25) NOT NULL, email_responsavel VARCHAR(190) NOT NULL, serie_pretendida VARCHAR(100) NOT NULL, periodo ENUM('Manhã','Tarde','Noite') NOT NULL, ano_letivo SMALLINT UNSIGNED NOT NULL, escola_anterior VARCHAR(200) NOT NULL DEFAULT '', observacoes TEXT NULL, email_acesso VARCHAR(190) NOT NULL UNIQUE, senha_hash VARCHAR(255) NOT NULL, status ENUM('email_nao_verificado','pendente','em_analise','aprovada','reprovada','cancelada') NOT NULL DEFAULT 'pendente', motivo_reprovacao TEXT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, analisado_em DATETIME NULL, analisado_por BIGINT UNSIGNED NULL,
  INDEX (status),
  INDEX (cpf_aluno),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (analisado_por) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS anos_letivos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ano SMALLINT UNSIGNED NOT NULL UNIQUE, data_inicio DATE NOT NULL, data_fim DATE NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo',
  CHECK (data_fim>=data_inicio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bimestres (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ano_letivo_id BIGINT UNSIGNED NOT NULL, numero TINYINT UNSIGNED NOT NULL, nome VARCHAR(60) NOT NULL, data_inicio DATE NOT NULL, data_fim DATE NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo',
  UNIQUE (ano_letivo_id,numero),
  CHECK (numero BETWEEN 1 AND 4),
  CHECK (data_fim>=data_inicio),
  FOREIGN KEY (ano_letivo_id) REFERENCES anos_letivos(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS turmas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL, serie VARCHAR(100) NOT NULL, curso VARCHAR(100) NOT NULL DEFAULT '', periodo ENUM('Manhã','Tarde','Noite') NOT NULL, ano_letivo SMALLINT UNSIGNED NOT NULL, sala VARCHAR(40) NOT NULL DEFAULT '', capacidade SMALLINT UNSIGNED NOT NULL DEFAULT 40, professor_responsavel_id BIGINT UNSIGNED NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ano_letivo) REFERENCES anos_letivos(ano) ON DELETE RESTRICT ON UPDATE RESTRICT,
  UNIQUE (nome,ano_letivo),
  FOREIGN KEY (professor_responsavel_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS disciplinas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL UNIQUE, codigo VARCHAR(40) NULL UNIQUE, carga_horaria DECIMAL(6,2) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS turma_disciplina (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL,
  UNIQUE (turma_id,disciplina_id),
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS professor_disciplina (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  professor_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL,
  UNIQUE (professor_id,disciplina_id),
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS professor_turma (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL,
  UNIQUE (professor_id,turma_id,disciplina_id),
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS aluno_turma (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  aluno_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, data_inicio DATE NOT NULL, data_fim DATE NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo',
  UNIQUE (aluno_id,turma_id),
  INDEX (turma_id,status),
  FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS avaliacoes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, bimestre_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, tipo ENUM('atividade','trabalho','prova','projeto','recuperacao') NOT NULL, valor_maximo DECIMAL(7,2) NOT NULL, data_avaliacao DATE NOT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (valor_maximo>0),
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (bimestre_id) REFERENCES bimestres(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  avaliacao_id BIGINT UNSIGNED NOT NULL, aluno_id BIGINT UNSIGNED NOT NULL, nota DECIMAL(7,2) NOT NULL, observacao TEXT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (avaliacao_id,aluno_id),
  CHECK (nota>=0),
  FOREIGN KEY (avaliacao_id) REFERENCES avaliacoes(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chamadas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NOT NULL, data_aula DATE NOT NULL, numero_aula TINYINT UNSIGNED NOT NULL DEFAULT 1, horario_inicio TIME NULL, horario_fim TIME NULL, conteudo TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'registrada', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (turma_id,disciplina_id,data_aula,numero_aula),
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS presencas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  chamada_id BIGINT UNSIGNED NOT NULL, aluno_id BIGINT UNSIGNED NOT NULL, status ENUM('presente','falta','justificada') NOT NULL, observacao VARCHAR(500) NOT NULL DEFAULT '',
  UNIQUE (chamada_id,aluno_id),
  FOREIGN KEY (chamada_id) REFERENCES chamadas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS atividades (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, descricao TEXT NOT NULL, tipo VARCHAR(30) NOT NULL, valor DECIMAL(7,2) NOT NULL, data_publicacao DATE NOT NULL, data_entrega DATE NOT NULL, status VARCHAR(30) NOT NULL, material VARCHAR(1000) NOT NULL DEFAULT '', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS conteudos_aulas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, descricao TEXT NOT NULL, data_aula DATE NOT NULL, numero_aula TINYINT UNSIGNED NOT NULL, objetivo TEXT NOT NULL, metodologia TEXT NOT NULL, material VARCHAR(1000) NOT NULL DEFAULT '', observacao TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'ativo', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ocorrencias (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  aluno_id BIGINT UNSIGNED NOT NULL, registrado_por BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NULL, categoria VARCHAR(100) NOT NULL, descricao TEXT NOT NULL, observacao TEXT NULL, status VARCHAR(30) NOT NULL, data_ocorrencia DATE NOT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (aluno_id) REFERENCES alunos(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (registrado_por) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS comunicados (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  autor_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, mensagem TEXT NOT NULL, publico ENUM('todos','diretores','coordenadores','professores','alunos','responsaveis','turma') NOT NULL, turma_id BIGINT UNSIGNED NULL, data_publicacao DATE NOT NULL, destaque BOOLEAN NOT NULL DEFAULT 0, status VARCHAR(30) NOT NULL DEFAULT 'ativo', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (autor_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notificacoes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, mensagem TEXT NULL, tipo VARCHAR(40) NOT NULL, link VARCHAR(200) NOT NULL, lida BOOLEAN NOT NULL DEFAULT 0, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (usuario_id,lida,criado_em),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pontos_professores (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  professor_id BIGINT UNSIGNED NOT NULL, data DATE NOT NULL, entrada DATETIME NOT NULL, saida DATETIME NULL, status VARCHAR(30) NOT NULL, observacao TEXT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (professor_id,data),
  CHECK (saida IS NULL OR saida>=entrada),
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS solicitacoes_ajuste_ponto (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ponto_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NOT NULL, entrada_solicitada DATETIME NOT NULL, saida_solicitada DATETIME NULL, motivo TEXT NOT NULL, status ENUM('pendente','aprovado','rejeitado') NOT NULL DEFAULT 'pendente', analisado_por BIGINT UNSIGNED NULL, analisado_em DATETIME NULL, parecer TEXT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ponto_id) REFERENCES pontos_professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (analisado_por) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS horarios_aulas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  turma_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, dia_semana TINYINT UNSIGNED NOT NULL, hora_inicio TIME NOT NULL, hora_fim TIME NOT NULL, sala VARCHAR(40) NOT NULL DEFAULT '',
  CHECK (dia_semana BETWEEN 1 AND 6),
  CHECK (hora_fim>hora_inicio),
  UNIQUE (professor_id,dia_semana,hora_inicio),
  FOREIGN KEY (turma_id) REFERENCES turmas(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (professor_id) REFERENCES professores(id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS logs_auditoria (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NULL, acao VARCHAR(150) NOT NULL, entidade VARCHAR(80) NOT NULL, entidade_id VARCHAR(80) NULL, descricao TEXT NULL, ip VARCHAR(45) NOT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (criado_em),
  INDEX (entidade,entidade_id),
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS configuracoes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL DEFAULT 'Colégio Legado', email VARCHAR(190) NOT NULL DEFAULT '', endereco VARCHAR(500) NOT NULL DEFAULT '', ano_atual SMALLINT UNSIGNED NOT NULL, bimestre_atual TINYINT UNSIGNED NOT NULL DEFAULT 1, media_minima DECIMAL(4,2) NOT NULL DEFAULT 6, periodo VARCHAR(20) NOT NULL DEFAULT 'Manhã'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tentativas_login (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ip VARCHAR(45) NOT NULL, criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (ip,criado_em)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS recuperacoes_acesso (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(190) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS limites_email (
  chave CHAR(64) CHARACTER SET ascii COLLATE ascii_bin PRIMARY KEY,
  inicio DATETIME NOT NULL, tentativas INT UNSIGNED NOT NULL DEFAULT 0,
  INDEX idx_limites_inicio (inicio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Importar uma única vez em banco vazio.
INSERT INTO configuracoes (id,ano_atual) VALUES (1,YEAR(CURRENT_DATE));
INSERT INTO usuarios (nome,email,senha_hash,cargo,email_verificacao_exigida) VALUES ('Diretor','diretor@gmail.com','$2y$10$hh70NlS2RmwWI.0EWFiHvO9rFPZTeAivP5OECUZ/V4uESdLNZOo7G','diretor',0);
INSERT INTO diretores (usuario_id) VALUES (LAST_INSERT_ID());
INSERT INTO usuarios (nome,email,senha_hash,cargo,email_verificacao_exigida) VALUES ('Coordenador','coordenador@gmail.com','$2y$10$gxOyJZlcLc0WOJpjkBG94.vZBqrK6LsmlKJmxidA6D7P.jFAUfMdO','coordenador',0);
INSERT INTO coordenadores (usuario_id) VALUES (LAST_INSERT_ID());
INSERT INTO usuarios (nome,email,senha_hash,cargo,email_verificacao_exigida) VALUES ('Professor','professor@gmail.com','$2y$10$.C5c/vNnMDSutzYrheZfm.OfSTAKda2e3R14HeILYGVy8uVZi11WK','professor',0);
INSERT INTO professores (usuario_id) VALUES (LAST_INSERT_ID());
