-- ATENÇÃO: APAGA DEFINITIVAMENTE TODOS OS DADOS DO COLÉGIO LEGADO.
-- Exporte um backup no phpMyAdmin antes de executar.
USE colegio_legado;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE limites_email;
TRUNCATE TABLE recuperacoes_acesso;
TRUNCATE TABLE tentativas_login;
TRUNCATE TABLE configuracoes;
TRUNCATE TABLE logs_auditoria;
TRUNCATE TABLE horarios_aulas;
TRUNCATE TABLE solicitacoes_ajuste_ponto;
TRUNCATE TABLE pontos_professores;
TRUNCATE TABLE notificacoes;
TRUNCATE TABLE comunicados;
TRUNCATE TABLE ocorrencias;
TRUNCATE TABLE conteudos_aulas;
TRUNCATE TABLE atividades;
TRUNCATE TABLE presencas;
TRUNCATE TABLE chamadas;
TRUNCATE TABLE notas;
TRUNCATE TABLE avaliacoes;
TRUNCATE TABLE aluno_turma;
TRUNCATE TABLE professor_turma;
TRUNCATE TABLE professor_disciplina;
TRUNCATE TABLE turma_disciplina;
TRUNCATE TABLE disciplinas;
TRUNCATE TABLE turmas;
TRUNCATE TABLE bimestres;
TRUNCATE TABLE anos_letivos;
TRUNCATE TABLE solicitacoes_matricula;
TRUNCATE TABLE responsavel_aluno;
TRUNCATE TABLE responsaveis;
TRUNCATE TABLE alunos;
TRUNCATE TABLE professores;
TRUNCATE TABLE coordenadores;
TRUNCATE TABLE diretores;
TRUNCATE TABLE usuarios;
SET FOREIGN_KEY_CHECKS=1;
INSERT INTO configuracoes (id,ano_atual) VALUES (1,YEAR(CURRENT_DATE));
INSERT INTO usuarios (nome,email,senha_hash,cargo,email_verificacao_exigida) VALUES ('Diretor','diretor@gmail.com','$2y$10$hh70NlS2RmwWI.0EWFiHvO9rFPZTeAivP5OECUZ/V4uESdLNZOo7G','diretor',0);
INSERT INTO diretores (usuario_id) VALUES (LAST_INSERT_ID());
INSERT INTO usuarios (nome,email,senha_hash,cargo,email_verificacao_exigida) VALUES ('Coordenador','coordenador@gmail.com','$2y$10$gxOyJZlcLc0WOJpjkBG94.vZBqrK6LsmlKJmxidA6D7P.jFAUfMdO','coordenador',0);
INSERT INTO coordenadores (usuario_id) VALUES (LAST_INSERT_ID());
INSERT INTO usuarios (nome,email,senha_hash,cargo,email_verificacao_exigida) VALUES ('Professor','professor@gmail.com','$2y$10$.C5c/vNnMDSutzYrheZfm.OfSTAKda2e3R14HeILYGVy8uVZi11WK','professor',0);
INSERT INTO professores (usuario_id) VALUES (LAST_INSERT_ID());
