<?php
// Gera os dois arquivos importáveis; não acessa nem altera o banco.
declare(strict_types=1);
$created='criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP';
$updated='atualizado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP';
$status="status VARCHAR(30) NOT NULL DEFAULT 'ativo'";
$tables=[];
function table(string $name,string $columns,array $refs=[],array $extras=[]): void {
    global $tables;
    $parts=['id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY',$columns,...$extras];
    foreach($refs as $col=>$target)$parts[]="FOREIGN KEY ($col) REFERENCES $target(id) ON UPDATE RESTRICT ON DELETE RESTRICT";
    $tables[$name]="CREATE TABLE IF NOT EXISTS $name (\n  ".implode(",\n  ",$parts)."\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n";
}
table('usuarios',"nome VARCHAR(200) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, senha_hash VARCHAR(255) NOT NULL, cargo ENUM('diretor','coordenador','professor','aluno','responsavel') NOT NULL, status ENUM('ativo','inativo','bloqueado','pendente') NOT NULL DEFAULT 'ativo', primeiro_acesso BOOLEAN NOT NULL DEFAULT 0, ultimo_acesso DATETIME NULL, telefone VARCHAR(25) NOT NULL DEFAULT '', foto MEDIUMTEXT NULL, notificacoes BOOLEAN NOT NULL DEFAULT 1, $created, $updated");
foreach(['diretores','coordenadores'] as $t)table($t,"usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, cpf CHAR(11) NULL UNIQUE, telefone VARCHAR(25) NOT NULL DEFAULT '', $created",['usuario_id'=>'usuarios']);
table('professores',"usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, matricula VARCHAR(40) NULL UNIQUE, cpf CHAR(11) NULL UNIQUE, telefone VARCHAR(25) NOT NULL DEFAULT '', data_nascimento DATE NULL, data_admissao DATE NULL, carga_horaria DECIMAL(6,2) NOT NULL DEFAULT 0, horario_previsto TIME NULL, $status, $created, $updated",['usuario_id'=>'usuarios']);
table('alunos',"usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, matricula VARCHAR(40) NOT NULL UNIQUE, nome VARCHAR(200) NOT NULL, cpf CHAR(11) NULL UNIQUE, rg VARCHAR(30) NOT NULL DEFAULT '', data_nascimento DATE NOT NULL, telefone VARCHAR(25) NOT NULL, email VARCHAR(190) NOT NULL, cep VARCHAR(9) NOT NULL, logradouro VARCHAR(200) NOT NULL, numero VARCHAR(20) NOT NULL, complemento VARCHAR(150) NOT NULL DEFAULT '', bairro VARCHAR(100) NOT NULL, cidade VARCHAR(100) NOT NULL, estado CHAR(2) NOT NULL, endereco_formatado VARCHAR(500) NULL, foto MEDIUMTEXT NULL, $status, data_ingresso DATE NOT NULL, $created, $updated",['usuario_id'=>'usuarios']);
table('responsaveis',"usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, nome VARCHAR(200) NOT NULL, cpf CHAR(11) NOT NULL UNIQUE, telefone VARCHAR(25) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, $created",['usuario_id'=>'usuarios']);
table('responsavel_aluno',"responsavel_id BIGINT UNSIGNED NOT NULL, aluno_id BIGINT UNSIGNED NOT NULL, parentesco VARCHAR(40) NOT NULL, responsavel_principal BOOLEAN NOT NULL DEFAULT 1",['responsavel_id'=>'responsaveis','aluno_id'=>'alunos'],['UNIQUE (responsavel_id,aluno_id)']);
table('solicitacoes_matricula',"usuario_id BIGINT UNSIGNED NOT NULL UNIQUE, aluno_id BIGINT UNSIGNED NULL, nome_aluno VARCHAR(200) NOT NULL, cpf_aluno CHAR(11) NOT NULL, rg_aluno VARCHAR(30) NOT NULL DEFAULT '', data_nascimento DATE NOT NULL, telefone_aluno VARCHAR(25) NOT NULL, email_aluno VARCHAR(190) NOT NULL, cep VARCHAR(9) NOT NULL, logradouro VARCHAR(200) NOT NULL, numero VARCHAR(20) NOT NULL, complemento VARCHAR(150) NOT NULL DEFAULT '', bairro VARCHAR(100) NOT NULL, cidade VARCHAR(100) NOT NULL, estado CHAR(2) NOT NULL, nome_responsavel VARCHAR(200) NOT NULL, cpf_responsavel CHAR(11) NOT NULL, parentesco VARCHAR(40) NOT NULL, telefone_responsavel VARCHAR(25) NOT NULL, email_responsavel VARCHAR(190) NOT NULL, serie_pretendida VARCHAR(100) NOT NULL, periodo ENUM('Manhã','Tarde','Noite') NOT NULL, ano_letivo SMALLINT UNSIGNED NOT NULL, escola_anterior VARCHAR(200) NOT NULL DEFAULT '', observacoes TEXT NULL, email_acesso VARCHAR(190) NOT NULL UNIQUE, senha_hash VARCHAR(255) NOT NULL, status ENUM('pendente','em_analise','aprovada','reprovada','cancelada') NOT NULL DEFAULT 'pendente', motivo_reprovacao TEXT NULL, $created, analisado_em DATETIME NULL, analisado_por BIGINT UNSIGNED NULL",['usuario_id'=>'usuarios','aluno_id'=>'alunos','analisado_por'=>'usuarios'],['INDEX (status)','INDEX (cpf_aluno)']);
table('anos_letivos',"ano SMALLINT UNSIGNED NOT NULL UNIQUE, data_inicio DATE NOT NULL, data_fim DATE NOT NULL, $status",[],['CHECK (data_fim>=data_inicio)']);
table('bimestres',"ano_letivo_id BIGINT UNSIGNED NOT NULL, numero TINYINT UNSIGNED NOT NULL, nome VARCHAR(60) NOT NULL, data_inicio DATE NOT NULL, data_fim DATE NOT NULL, $status",['ano_letivo_id'=>'anos_letivos'],['UNIQUE (ano_letivo_id,numero)','CHECK (numero BETWEEN 1 AND 4)','CHECK (data_fim>=data_inicio)']);
table('turmas',"nome VARCHAR(150) NOT NULL, serie VARCHAR(100) NOT NULL, curso VARCHAR(100) NOT NULL DEFAULT '', periodo ENUM('Manhã','Tarde','Noite') NOT NULL, ano_letivo SMALLINT UNSIGNED NOT NULL, sala VARCHAR(40) NOT NULL DEFAULT '', capacidade SMALLINT UNSIGNED NOT NULL DEFAULT 40, professor_responsavel_id BIGINT UNSIGNED NULL, $status, $created",['professor_responsavel_id'=>'professores'],['FOREIGN KEY (ano_letivo) REFERENCES anos_letivos(ano) ON DELETE RESTRICT ON UPDATE RESTRICT','UNIQUE (nome,ano_letivo)']);
table('disciplinas',"nome VARCHAR(120) NOT NULL UNIQUE, codigo VARCHAR(40) NULL UNIQUE, carga_horaria DECIMAL(6,2) NOT NULL, $status");
table('turma_disciplina','turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL',['turma_id'=>'turmas','disciplina_id'=>'disciplinas'],['UNIQUE (turma_id,disciplina_id)']);
table('professor_disciplina','professor_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL',['professor_id'=>'professores','disciplina_id'=>'disciplinas'],['UNIQUE (professor_id,disciplina_id)']);
table('professor_turma','professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL',['professor_id'=>'professores','turma_id'=>'turmas','disciplina_id'=>'disciplinas'],['UNIQUE (professor_id,turma_id,disciplina_id)']);
table('aluno_turma',"aluno_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, data_inicio DATE NOT NULL, data_fim DATE NULL, $status",['aluno_id'=>'alunos','turma_id'=>'turmas'],['UNIQUE (aluno_id,turma_id)','INDEX (turma_id,status)']);
table('avaliacoes',"professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, bimestre_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, tipo ENUM('atividade','trabalho','prova','projeto','recuperacao') NOT NULL, valor_maximo DECIMAL(7,2) NOT NULL, data_avaliacao DATE NOT NULL, $created",['professor_id'=>'professores','turma_id'=>'turmas','disciplina_id'=>'disciplinas','bimestre_id'=>'bimestres'],['CHECK (valor_maximo>0)']);
table('notas',"avaliacao_id BIGINT UNSIGNED NOT NULL, aluno_id BIGINT UNSIGNED NOT NULL, nota DECIMAL(7,2) NOT NULL, observacao TEXT NULL, $created, $updated",['avaliacao_id'=>'avaliacoes','aluno_id'=>'alunos'],['UNIQUE (avaliacao_id,aluno_id)','CHECK (nota>=0)']);
table('chamadas',"turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NOT NULL, data_aula DATE NOT NULL, numero_aula TINYINT UNSIGNED NOT NULL DEFAULT 1, horario_inicio TIME NULL, horario_fim TIME NULL, conteudo TEXT NULL, status VARCHAR(30) NOT NULL DEFAULT 'registrada', $created",['turma_id'=>'turmas','disciplina_id'=>'disciplinas','professor_id'=>'professores'],['UNIQUE (turma_id,disciplina_id,data_aula,numero_aula)']);
table('presencas',"chamada_id BIGINT UNSIGNED NOT NULL, aluno_id BIGINT UNSIGNED NOT NULL, status ENUM('presente','falta','justificada') NOT NULL, observacao VARCHAR(500) NOT NULL DEFAULT ''",['chamada_id'=>'chamadas','aluno_id'=>'alunos'],['UNIQUE (chamada_id,aluno_id)']);
table('atividades',"professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, descricao TEXT NOT NULL, tipo VARCHAR(30) NOT NULL, valor DECIMAL(7,2) NOT NULL, data_publicacao DATE NOT NULL, data_entrega DATE NOT NULL, status VARCHAR(30) NOT NULL, material VARCHAR(1000) NOT NULL DEFAULT '', $created, $updated",['professor_id'=>'professores','turma_id'=>'turmas','disciplina_id'=>'disciplinas']);
table('conteudos_aulas',"professor_id BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, descricao TEXT NOT NULL, data_aula DATE NOT NULL, numero_aula TINYINT UNSIGNED NOT NULL, objetivo TEXT NOT NULL, metodologia TEXT NOT NULL, material VARCHAR(1000) NOT NULL DEFAULT '', observacao TEXT NULL, $status, $created",['professor_id'=>'professores','turma_id'=>'turmas','disciplina_id'=>'disciplinas']);
table('ocorrencias',"aluno_id BIGINT UNSIGNED NOT NULL, registrado_por BIGINT UNSIGNED NOT NULL, turma_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NULL, categoria VARCHAR(100) NOT NULL, descricao TEXT NOT NULL, observacao TEXT NULL, status VARCHAR(30) NOT NULL, data_ocorrencia DATE NOT NULL, $created",['aluno_id'=>'alunos','registrado_por'=>'usuarios','turma_id'=>'turmas','professor_id'=>'professores']);
table('comunicados',"autor_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, mensagem TEXT NOT NULL, publico ENUM('todos','diretores','coordenadores','professores','alunos','responsaveis','turma') NOT NULL, turma_id BIGINT UNSIGNED NULL, data_publicacao DATE NOT NULL, destaque BOOLEAN NOT NULL DEFAULT 0, $status, $created",['autor_id'=>'usuarios','turma_id'=>'turmas']);
table('notificacoes',"usuario_id BIGINT UNSIGNED NOT NULL, titulo VARCHAR(200) NOT NULL, mensagem TEXT NULL, tipo VARCHAR(40) NOT NULL, link VARCHAR(200) NOT NULL, lida BOOLEAN NOT NULL DEFAULT 0, $created",['usuario_id'=>'usuarios'],['INDEX (usuario_id,lida,criado_em)']);
table('pontos_professores',"professor_id BIGINT UNSIGNED NOT NULL, data DATE NOT NULL, entrada DATETIME NOT NULL, saida DATETIME NULL, status VARCHAR(30) NOT NULL, observacao TEXT NULL, $created, $updated",['professor_id'=>'professores'],['UNIQUE (professor_id,data)','CHECK (saida IS NULL OR saida>=entrada)']);
table('solicitacoes_ajuste_ponto',"ponto_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NOT NULL, entrada_solicitada DATETIME NOT NULL, saida_solicitada DATETIME NULL, motivo TEXT NOT NULL, status ENUM('pendente','aprovado','rejeitado') NOT NULL DEFAULT 'pendente', analisado_por BIGINT UNSIGNED NULL, analisado_em DATETIME NULL, parecer TEXT NULL, $created",['ponto_id'=>'pontos_professores','professor_id'=>'professores','analisado_por'=>'usuarios']);
table('horarios_aulas',"turma_id BIGINT UNSIGNED NOT NULL, professor_id BIGINT UNSIGNED NOT NULL, disciplina_id BIGINT UNSIGNED NOT NULL, dia_semana TINYINT UNSIGNED NOT NULL, hora_inicio TIME NOT NULL, hora_fim TIME NOT NULL, sala VARCHAR(40) NOT NULL DEFAULT ''",['turma_id'=>'turmas','professor_id'=>'professores','disciplina_id'=>'disciplinas'],['CHECK (dia_semana BETWEEN 1 AND 6)','CHECK (hora_fim>hora_inicio)','UNIQUE (professor_id,dia_semana,hora_inicio)']);
table('logs_auditoria',"usuario_id BIGINT UNSIGNED NULL, acao VARCHAR(150) NOT NULL, entidade VARCHAR(80) NOT NULL, entidade_id VARCHAR(80) NULL, descricao TEXT NULL, ip VARCHAR(45) NOT NULL, $created",['usuario_id'=>'usuarios'],['INDEX (criado_em)','INDEX (entidade,entidade_id)']);
table('configuracoes',"nome VARCHAR(150) NOT NULL DEFAULT 'Colégio Legado', email VARCHAR(190) NOT NULL DEFAULT '', endereco VARCHAR(500) NOT NULL DEFAULT '', ano_atual SMALLINT UNSIGNED NOT NULL, bimestre_atual TINYINT UNSIGNED NOT NULL DEFAULT 1, media_minima DECIMAL(4,2) NOT NULL DEFAULT 6, periodo VARCHAR(20) NOT NULL DEFAULT 'Manhã'");
table('tentativas_login',"ip VARCHAR(45) NOT NULL, $created",[],['INDEX (ip,criado_em)']);
table('recuperacoes_acesso',"email VARCHAR(190) NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'pendente', $created");
$seed="INSERT INTO configuracoes (id,ano_atual) VALUES (1,YEAR(CURRENT_DATE));\n";
foreach(['diretor'=>'Diretor','coordenador'=>'Coordenador','professor'=>'Professor'] as $role=>$name){$hash=password_hash('123456',PASSWORD_DEFAULT);$seed.="INSERT INTO usuarios (nome,email,senha_hash,cargo) VALUES ('$name','$role@gmail.com','$hash','$role');\n";$tbl=['diretor'=>'diretores','coordenador'=>'coordenadores','professor'=>'professores'][$role];$seed.="INSERT INTO $tbl (usuario_id) VALUES (LAST_INSERT_ID());\n";}
$header="-- Colégio Legado: MySQL/MariaDB, sem dados acadêmicos iniciais.\nCREATE DATABASE IF NOT EXISTS colegio_legado CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\nUSE colegio_legado;\nSET NAMES utf8mb4;\n";
file_put_contents(__DIR__.'/../database/colegio_legado.sql',$header.implode("\n",$tables)."\n-- Importar uma única vez em banco vazio.\n".$seed);
$reset="-- ATENÇÃO: APAGA DEFINITIVAMENTE TODOS OS DADOS DO COLÉGIO LEGADO.\n-- Exporte um backup no phpMyAdmin antes de executar.\nUSE colegio_legado;\nSET FOREIGN_KEY_CHECKS=0;\n";
foreach(array_reverse(array_keys($tables)) as $t)$reset.="TRUNCATE TABLE $t;\n";
$reset.="SET FOREIGN_KEY_CHECKS=1;\n".$seed;
file_put_contents(__DIR__.'/../database/reset_database.sql',$reset);
echo count($tables)." tabelas; SQL e reset gerados.\n";
